version: "3.7"
volumes:
  object-cqrs-dbdata:
services:
  object-cqrs-db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: object-cqrs-db
    ports:
      - "15599:3306"
    environment:
      - MYSQL_DATABASE=object_cqrs
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - object-cqrs-dbdata:/var/lib/mysql8